// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjegKCvowPxdBQRpGvvG6gj60jbaj_b3I',
    appId: '1:827630250027:web:2082fbc1e857b043ef626e',
    messagingSenderId: '827630250027',
    projectId: 'home-finder-3d48b',
    authDomain: 'home-finder-3d48b.firebaseapp.com',
    storageBucket: 'home-finder-3d48b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbQcsnPGW54-UvLayycjRjzPc9zp-nomQ',
    appId: '1:827630250027:android:c7602b8cd27d4305ef626e',
    messagingSenderId: '827630250027',
    projectId: 'home-finder-3d48b',
    storageBucket: 'home-finder-3d48b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbaCEz9jqvmFJeTgEJdGCa3iuHfdx-Ns',
    appId: '1:827630250027:ios:8dec40efa326d5d5ef626e',
    messagingSenderId: '827630250027',
    projectId: 'home-finder-3d48b',
    storageBucket: 'home-finder-3d48b.appspot.com',
    iosClientId: '827630250027-icg3s045a4u60dj6ll7ptodnqq6oftu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTbaCEz9jqvmFJeTgEJdGCa3iuHfdx-Ns',
    appId: '1:827630250027:ios:8dec40efa326d5d5ef626e',
    messagingSenderId: '827630250027',
    projectId: 'home-finder-3d48b',
    storageBucket: 'home-finder-3d48b.appspot.com',
    iosClientId: '827630250027-icg3s045a4u60dj6ll7ptodnqq6oftu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeFinder',
  );
}
